ktor:
  application:
    modules:
      - ru.drujite.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  audience: "drujite-audience"
  issuer: "http://localhost/"
  realm: "ktor sample app"
  secret: $JWT_SECRET
postgres:
  url: "jdbc:postgresql://pg:25432/drujite_pg"
  user: admin
  password: password